[package]
name = "elara-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elara_log = "0.1.0"
matrixmultiply = "0.3.7"
transpose = "0.2.2"
